name: cfn-lint
on:
  push:
    paths:
      - 'stacks/*'
      - 'integ/stacks/*'
  pull_request:
    paths:
      - 'stacks/*'
      - 'integ/stacks/*'
jobs:
  cfn-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - run: pip install cfn-lint
      - run: make cfn-lint
