name: cfn-lint
on:
  push:
    paths:
      - 'stacks/*'
      - 'integ/stacks/*'
  pull_request:
    paths:
      - 'stacks/*'
      - 'integ/stacks/*'
jobs:
  cfn-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - run: pip install cfn-lint
      - run: make cfn-lint
