name: cfn-lint
on:
  push:
    paths:
      - 'stacks/*'
      - 'integ/stacks/*'
  pull_request:
    paths:
      - 'stacks/*'
      - 'integ/stacks/*'
jobs:
  cfn-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - run: pip install cfn-lint
      - run: make cfn-lint
