name: Updater CI
on:
  pull_request:
    branches: [develop]
  # TODO - remove fargate branch from this once CI is confirmed to work
  push:
    branches: [fargate, develop]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: rustup update stable && cargo install -f cargo-deny
      - run: make ci
